
name: template_test


on:
  repository_dispatch:
    types:
      - template_test
  push:
    branches: [ '*' ]
  pull_request:
  release:
    types: [ created, edited ]
  workflow_dispatch:
    inputs:
      gva_version:
        required: true
        type: string
# env:
  # sss
env:
  TZ: Asia/Shanghai
jobs:
  init:
    if: github.repository_owner == 'charlessoft'
    # runs-on: ubuntu-latest
    runs-on: macos-latest
    steps:
      - name: init
        run: |
          echo "charlessoft"
          echo "${{ toJson(github.event.client_payload) }}"
          echo "charlessoft11"
          echo "${{ toJson(github.event.client_payload) }}" > client_payload.json


  dingding-error:
    runs-on: ubuntu-latest
    needs: [frontend]
    if: ${{ failure() }}
    steps:
      - uses: actions/checkout@v4
      - name: Send dingding notify error
        uses: zcong1993/actions-ding@master
        with:
          dingToken: ${{ github.event.client_payload.dding_token.token }} #钉钉token
          secret: ${{ github.event.client_payload.dding_token.secret }}
          body: |
            {
              "msgtype": "text",
              "text": {
                  "content": 'status:[打叉][打叉][打叉]  ${{ github.event.client_payload.ext.repository }} 执行失败\n提交者:  ${{ github.event.client_payload.ext.pusher.username }}\n${{ github.ref_type }}: ${{ github.event.client_payload.mybranch }}\nlog: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}'
             }
             }
            

  dingding-success:
    runs-on: ubuntu-latest
    if: ${{ success() }}
    needs: [frontend]
    steps:
      - uses: actions/checkout@v4
      - name: Send dingding notify success
        uses: zcong1993/actions-ding@master
        with:
          dingToken: ${{ github.event.client_payload.dding_token.token }} #钉钉token
          secret: ${{ github.event.client_payload.dding_token.secret }}
          body: |
            {
             "msgtype": "text",
             "text": {
                 "content": 'status:[对勾][对勾][对勾][100分]  ${{ github.event.client_payload.ext.repository }} 执行成功\n提交者: ${{ github.event.client_payload.ext.pusher.username }}\n${{ github.ref_type }}: ${{ github.event.client_payload.mybranch }}\nlog: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}'
             }
             }