
name: template_test


on:
  repository_dispatch:
    types:
      - template_test
  push:
    branches: [ '*' ]
  pull_request:
  release:
    types: [ created, edited ]
  workflow_dispatch:
    inputs:
      gva_version:
        required: true
        type: string
# env:
  # sss
env:
  TZ: Asia/Shanghai
jobs:
  init:
    if: github.repository_owner == 'charlessoft'
    # runs-on: ubuntu-latest
    runs-on: macos-latest
    steps:
      - name: init
        run: |
          echo "charlessoft"
          echo "${{ toJson(github.event.client_payload) }}"
          echo "charlessoft11"
          echo "${{ toJson(github.event.client_payload) }}" > client_payload.json


  dingding-error:
    runs-on: ubuntu-latest
    needs: [init]
    if: ${{ failure() }}
    steps:
      - uses: actions/checkout@v4
      - name: Send dingding notify error
        uses: zcong1993/actions-ding@master
        with:
          dingToken: ${{ github.event.client_payload.dding_token.token }} #钉钉token
          secret: ${{ github.event.client_payload.dding_token.secret }}
          body: |
            {
              "msgtype": "text",
              "text": {
                  "content": '[打叉][打叉][打叉]  执行失败\n提交者: ${{ github.triggering_actor }}\n任务: ${{ github.event.pull_request.title }}\n${{ github.ref_type }}: ${{ github.event.client_payload }}\n${{ github.event_name }}: ${{ github.server_url }}/${{ github.repository }}/pull/${{ github.event.number }}'
             }
             }
            

  dingding-success:
    runs-on: ubuntu-latest
    if: ${{ success() }}
    needs: [init]
    steps:
      - uses: actions/checkout@v4
      - name: Send dingding notify success
        uses: zcong1993/actions-ding@master
        with:
          dingToken: ${{ github.event.client_payload.dding_token.token }} #钉钉token
          secret: ${{ github.event.client_payload.dding_token.secret }}
          body: |
            {
             "msgtype": "text",
             "text": {
                 "content": '[微笑][微笑][微笑]  执行成功\n提交者: ${{ github.triggering_actor }}\n任务: ${{ github.event.pull_request.title }}\n${{ github.ref_type }}: ${{ github.head_ref }}\n${{ github.event_name }}: ${{ github.server_url }}/${{ github.repository }}/pull/${{ github.event.number }}'
             }
             }
